# Define shell
SHELL = csh

all:

	/usr/projects/vpic/guofan/vpic/build/bin/vpic reconnection.cc

cleanall: 	
#	cd translate; make clean 
	-rm data/*
	-rm -rf hydro
	-rm -rf particle
	-rm -rf restart*
	-rm -rf rundata
	-rm -rf fields
#	-rm translate
	-rm *.op
	-rm *.ppu
	-rm *.vpc
	-rm outfile
	-rm info
	-rm *.eps
	-rm *.mpg
	-rm core.*
	-rm *~









